# Generated by Django 4.2.5 on 2023-10-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ismpr_client', '0002_alter_client_options_alter_clientequipment_options_and_more'),
        ('ismpr_worker', '0002_alter_worker_options_alter_workerstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование статусов')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуги',
            },
        ),
        migrations.CreateModel(
            name='ClientOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOrder', models.DateField(verbose_name='Дата выполнения заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_client.client', verbose_name='Клиент')),
                ('clientEquipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_client.clientequipment', verbose_name='Оборудование клиента')),
                ('orderStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_orders.orderstatus', verbose_name='Текущий статус заявки')),
                ('typeService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_orders.typeservice', verbose_name='Тип сервиса')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_worker.worker', verbose_name='Работник принявший заявку')),
            ],
        ),
    ]
