# Generated by Django 4.2.5 on 2023-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorders',
            options={'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип услуги'),
        ),
    ]
