# Generated by Django 4.2.5 on 2023-10-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_worker', '0002_alter_worker_phone'),
        ('ismpr_orders', '0002_alter_clientorders_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorders',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrder', to='ismpr_worker.worker', verbose_name='Работник принявший заявку'),
        ),
    ]
