# Generated by Django 4.2.5 on 2023-10-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ismpr_orders', '0003_alter_clientorders_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReasonDescription', models.TextField(max_length=255)),
                ('clientOrders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_orders.clientorders', verbose_name='Отклоненные или Отмененные заявки')),
                ('whoRejected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отменивший заявку')),
            ],
        ),
    ]
