# Generated by Django 4.2.5 on 2023-10-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0005_alter_rejectedorders_clientorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedorders',
            name='clientOrders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_orders.clientorders', verbose_name='Отклоненные или Отмененные заявки'),
        ),
    ]
