# Generated by Django 4.2.5 on 2023-10-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_client', '0001_initial'),
        ('ismpr_worker', '0002_alter_worker_phone'),
        ('ismpr_orders', '0006_alter_rejectedorders_clientorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedorders',
            name='clientOrders',
        ),
        migrations.AddField(
            model_name='rejectedorders',
            name='InfoOrder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='clientEquipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_client.clientequipment', verbose_name='Оборудование клиента'),
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='orderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_orders.orderstatus', verbose_name='Текущий статус заявки'),
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='typeService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_orders.typeservice', verbose_name='Тип сервиса'),
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ismpr_worker.worker', verbose_name='Работник принявший заявку'),
        ),
        migrations.AlterField(
            model_name='rejectedorders',
            name='ReasonDescription',
            field=models.TextField(max_length=255, verbose_name='Причина отклонения'),
        ),
    ]
