# Generated by Django 4.2.5 on 2023-11-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0007_remove_rejectedorders_clientorders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectedorders',
            options={'verbose_name': 'Отмененная заявка клиента', 'verbose_name_plural': 'Отмененные заявки клиентов'},
        ),
    ]
