# Generated by Django 4.2.5 on 2023-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0008_alter_rejectedorders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='isActiveStatus',
            field=models.BooleanField(null=True, verbose_name='Активный?'),
        ),
        migrations.AlterField(
            model_name='rejectedorders',
            name='InfoOrder',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о Заявке'),
        ),
    ]
