# Generated by Django 4.2.5 on 2024-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0009_orderstatus_isactivestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorders',
            name='problemDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проблемы'),
        ),
    ]
