# Generated by Django 4.2.5 on 2024-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0010_clientorders_problemdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedorders',
            name='ReasonDescription',
            field=models.TextField(max_length=255, null=True, verbose_name='Причина отклонения'),
        ),
    ]
