# Generated by Django 4.2.5 on 2024-04-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_orders', '0011_alter_rejectedorders_reasondescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackDescription', models.TextField(max_length=500, null=True, verbose_name='Комментарии')),
                ('Score', models.IntegerField(max_length=5, verbose_name='Оценка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_orders.clientorders', verbose_name='Номер заявки')),
            ],
        ),
    ]
