# Generated by Django 4.2.5 on 2023-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_ismpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
