# Generated by Django 4.2.5 on 2023-10-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_ismpr', '0002_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Surname',
        ),
    ]
