# Generated by Django 4.2.5 on 2023-10-12 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Введите корректный номер телефона.')]),
        ),
    ]
