# Generated by Django 4.2.5 on 2023-10-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='workerstatus',
            options={'verbose_name': 'Статус работника', 'verbose_name_plural': 'Статусы работников'},
        ),
    ]
