# Generated by Django 4.2.5 on 2024-03-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id_business', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('manufactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='ismpr_store.manufactor')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartsInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('spare_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_store.spareparts')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('spare_parts', models.ManyToManyField(related_name='stores', through='ismpr_store.SparePartsInStore', to='ismpr_store.spareparts')),
            ],
        ),
        migrations.AddField(
            model_name='sparepartsinstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_store.store'),
        ),
    ]
