# Generated by Django 4.2.5 on 2023-11-05 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ismpr_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.TextField(verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.CharField(max_length=12, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Логин клиента'),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='Company',
            field=models.CharField(max_length=50, verbose_name='Компания выдавшая оборудование'),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='Description',
            field=models.TextField(verbose_name='Описание оборудования'),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Название оборудования'),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientequipment',
            name='typeEquipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ismpr_client.typeequipment', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='typeequipment',
            name='description',
            field=models.TextField(verbose_name='Описание типа'),
        ),
        migrations.AlterField(
            model_name='typeequipment',
            name='type',
            field=models.CharField(max_length=50, verbose_name='тип оборудования'),
        ),
    ]
