# Generated by Django 4.2.5 on 2023-11-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ismpr_client', '0002_alter_client_address_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientequipment',
            options={'verbose_name': 'Оборудование клиента', 'verbose_name_plural': 'Оборудования клиентов'},
        ),
        migrations.AlterModelOptions(
            name='typeequipment',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
    ]
